import Head from 'next/head';
import { useState } from 'react';
import Create from '../components/Create';
import Modal from '../components/Modal';
import store from '../redux/store';
import { Provider } from 'react-redux';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <Provider store={store}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Create />
        <Modal />
      </div>
    </Provider>
  );
}
