import Head from 'next/head';
import { useState } from 'react';
import Create from '../components/Create';
import Modal from '../components/Modal';

import styles from '../styles/Home.module.css';

export default function Home() {
  const [isContact, setContact] = useState([]);

  const contact = (newNote) => {
    setContact((pre) => {
      return [...pre, newNote];
    });
  };
  const del = (id) => {
    setContact((pre) => {
      return pre.filter((item, index) => {
        return index !== id;
      });
    });
  };
  console.log(isContact);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Create add={contact} />
      {isContact.map((item, index) => (
        <Modal
          id={index}
          key={index}
          title={item.title}
          contact={item.contact}
          del={del}
        />
      ))}
    </div>
  );
}
